### ISSUE TITLE
请问 ChildOf 和 FollowsFrom 在时序图上的表达有什么差别

### ISSUE THREAD

**Issue by magicliang** [opentracing-contrib/opentracing-specification-zh#14]
按照文档中的例子：

ChildOf 引用的一个合理表述是：
 
 [-Parent Span---------]
         [-Child Span----]

FollowsFrom 引用的一个合理表述是：

 [-Parent Span--]
     [-Child Span-]

能否解释下这两个时序图除了-的长度不一样以外，图形中有什么特别的地方能够让读者看出来这是在描述一个 ChildOf 引用，还是在描述一个 FollowsFrom 引用？

**Comment by wu-sheng** [comment]
OpenTracing 已经不维护了，可以参加官网。这份翻译也不维护了。
