### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by lycheng** [opentracing-contrib/opentracing-specification-zh#4]
在 specification.md 中的 

https://github.com/opentracing-contrib/opentracing-specification-zh/blob/master/specification.md#span间关系

里面的 FollowsFrom 的解析

> 一些父级节点不以任何方式依然他们子节点的执行结果

应为

一些父级节点不以任何方式 依赖 他们子节点的执行结果

**Comment by wu-sheng** [comment]
已修复这个翻译问题，十分感谢。
