### ISSUE TITLE
需要更多资料

### ISSUE THREAD

**Issue by yyzybb537** [opentracing-contrib/opentracing-specification-zh#6]
你好，我和我的团队对opentracing很感兴趣，想要尝试一下，但是目前遇到三个问题没有找到相关资料：
1.标准文档和常见的博文都在讲opentracing-api的client代码应该怎么写，基本上没有介绍代码写完之后的流程，这一块能不能推荐一些资料？
比如：通过调用api传递的数据去了哪里(很多博文的示例代码中基本上都没有相关地址配置)？以什么方式传递给了处理后台(http接口？rpc接口？拖硬盘上的日志文件？还是其他什么方式？)？
2.兼容opentracing-api的处理后台目前大概知道几个，zipkin、dapper、jaeger等，但是不够系统，能不能列一个list出来，对比性的讲一讲每一个做了什么事情、适用于什么场景、优缺点、稳定性如何、能够应对多大规模的数据？
3.opentracing的立意里面提到了通过一层统一的api封装让用户可以简单切换不同处理后台，有没有具体的示例？

**Comment by wu-sheng** [comment]
> 1.标准文档和常见的博文都在讲opentracing-api的client代码应该怎么写，基本上没有介绍代码写完之后的流程，这一块能不能推荐一些资料？
比如：通过调用api传递的数据去了哪里(很多博文的示例代码中基本上都没有相关地址配置)？以什么方式传递给了处理后台(http接口？rpc接口？拖硬盘上的日志文件？还是其他什么方式？)？

因为OpenTracing只包含规范和API。你说的内容，不属于实现的范围。所以这些内容，请参考你使用的项目：
- Apache SkyWalking
- CNCF Jaeger
- Zipkin

> 2.兼容opentracing-api的处理后台目前大概知道几个，zipkin、dapper、jaeger等，但是不够系统，能不能列一个list出来，对比性的讲一讲每一个做了什么事情、适用于什么场景、优缺点、稳定性如何、能够应对多大规模的数据？

同1.没有所谓的支持场景和稳定性一说，这个由项目本身特性决定

> 3.opentracing的立意里面提到了通过一层统一的api封装让用户可以简单切换不同处理后台，有没有具体的示例？

关于切换实现，已经在文档中有描述，具体参见各语言的API说明

**Comment by yyzybb537** [comment]
所以就是只有一个空泛的标准咯？

**Comment by yyzybb537** [comment]
脱离了实现的标准  恐怕很难推动吧？

**Comment by wu-sheng** [comment]
> 所以就是只有一个空泛的标准咯？

标准需要厂商支持，这个是肯定的。能得到多大范围的支持，这个要看具体的运行情况。

**Comment by wu-sheng** [comment]
> 脱离了实现的标准 恐怕很难推动吧？

这个需要大家自行判断。

**Comment by yyzybb537** [comment]
那么作为标准的产出方，尚且不清楚自己标准被支持的程度吗

**Comment by wu-sheng** [comment]
> 那么作为标准的产出方，尚且不清楚自己标准被支持的程度吗

目前官方的支持列表在这里：http://opentracing.io/documentation/pages/supported-tracers  。支持和使用是完全不同两个维度。很多APM或者追踪系统，有自己的API。使用者是自己选择的。如：Apache SkyWalking本身提供了整套的自动探针方案，手动只是补充。

**Comment by IronsDu** [comment]
我记得 @wu-sheng 之前给某个RPC库提过一个issue，里面有给那个库作者提供一个实际的（其他项目）的做法/实现。 不过我也忘记是哪个库了。 我也想集成opentracing。

**Comment by wu-sheng** [comment]
motan, hprose-java
