### ISSUE TITLE
翻译欠妥

### ISSUE THREAD

**Issue by kuafou** [opentracing-contrib/opentracing-specification-zh#7]
在specification.md中：
https://github.com/opentracing-contrib/opentracing-specification-zh/blob/master/specification.md#%E9%99%A4%E4%BA%86%E9%80%9A%E8%BF%87span%E8%8E%B7%E5%8F%96spancontext
把`Retrieve the Spans SpanContext`翻译成`除了通过Span获取SpanContext`感觉欠妥。我认为可以翻译为`获取Span的SpanContext`。

**Comment by wu-sheng** [comment]
是的，你可以直接PR修改即可。

**Comment by kuafou** [comment]
> 是的，你可以直接PR修改即可。

好的
